package Telas;

import Classes.*;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ControleFinanceiroTela extends javax.swing.JFrame {
    
    Alunos a = new Alunos();
   ControleFinanceiro cf = new ControleFinanceiro();
    
    public ControleFinanceiroTela() {
        ResultSet rs;
        initComponents();
        carregarTabela();
       
        
        try {
            rs = a.selecionarAluno();
            if (rs != null) {
                while (rs.next()) {
                    boxAlunosCadastrados.addItem(rs.getString("matricula"));
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum"
                        + " Aluno cadastrado!");
            }        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ControleFinanceiroTela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ControleFinanceiroTela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void carregarTabela() {
        ResultSet rs;
        
        try {
            rs = cf.buscar();
            if (rs == null) {
                return;
            } else {
                Vector vetColuna = new Vector();
                vetColuna.add("Matricula");
                //vetColuna.add("Nome");
                vetColuna.add("Data Vencimento");
                vetColuna.add("Data Pagamento");
                vetColuna.add("Valor");
                //vetColuna.add("Situação");
                vetColuna.add("Método");
                Vector vetLinhas = new Vector();
                while (rs.next()) {
                    Vector vetLin = new Vector();
                    vetLin.add(rs.getString("codMatricula"));
                    //vetLin.add(buscarNomeAluno(rs.getString("nome")));
                    vetLin.add(rs.getString("dataVencimento"));
                    vetLin.add(rs.getString("dataPagamento"));
                    vetLin.add(rs.getString("valorMensalidade"));                   
                    //vetLin.add(rs.getString("situacaoPagamento"));
                    vetLin.add(rs.getString("formaPagamento"));
                    vetLinhas.add(vetLin);
                }
                tabela.setModel(new DefaultTableModel(vetLinhas, vetColuna));
            }//fecha o if
         } catch (ClassNotFoundException ex) {
            Logger.getLogger(ControleFinanceiroTela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ControleFinanceiroTela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }



  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        boxMetodo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        boxAlunosCadastrados = new javax.swing.JComboBox<>();
        boxPlano = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        botaoLancar = new javax.swing.JButton();
        boxDataPagamento = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        boxDataVencimento = new javax.swing.JFormattedTextField();
        boxValorMensal = new javax.swing.JTextField();
        boxValorPago = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        NomeAluno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle Financeiro");
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Pesquisar Aluno");
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(68, 151, 200, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Financeiro do Aluno");
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(68, 194, 200, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Plano de Mensalidade");
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(68, 247, 200, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Valor da Mensalidade");
        jLabel5.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel5.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(68, 295, 200, 20);

        tabela.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Nome", "Data Vencimento", "Data Pagamento", "Valor", "Situação", "Metodo Pagamento"
            }
        ));
        jScrollPane2.setViewportView(tabela);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 458, 1014, 119);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Valor Pagamento");
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel6.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(604, 290, 200, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Método de Pagamento");
        jLabel7.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel7.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(604, 151, 200, 20);

        boxMetodo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão", "Cheque", "Boleto" }));
        boxMetodo.setMaximumSize(new java.awt.Dimension(200, 30));
        boxMetodo.setMinimumSize(new java.awt.Dimension(200, 30));
        boxMetodo.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(boxMetodo);
        boxMetodo.setBounds(822, 146, 125, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Data de Pagamento");
        jLabel8.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(604, 199, 200, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Histórico do Aluno");
        jLabel9.setMaximumSize(new java.awt.Dimension(240, 30));
        jLabel9.setMinimumSize(new java.awt.Dimension(240, 30));
        jLabel9.setPreferredSize(new java.awt.Dimension(240, 30));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 376, 1014, 30);

        boxAlunosCadastrados.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxAlunosCadastrados.setMaximumSize(new java.awt.Dimension(200, 30));
        boxAlunosCadastrados.setMinimumSize(new java.awt.Dimension(200, 30));
        boxAlunosCadastrados.setPreferredSize(new java.awt.Dimension(200, 30));
        boxAlunosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAlunosCadastradosActionPerformed(evt);
            }
        });
        getContentPane().add(boxAlunosCadastrados);
        boxAlunosCadastrados.setBounds(286, 146, 300, 30);

        boxPlano.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensal", "Trimestral", "Semestral", "Anual" }));
        boxPlano.setMaximumSize(new java.awt.Dimension(200, 30));
        boxPlano.setMinimumSize(new java.awt.Dimension(200, 30));
        boxPlano.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(boxPlano);
        boxPlano.setBounds(286, 242, 150, 30);

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setMaximumSize(new java.awt.Dimension(150, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(150, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(150, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(556, 688, 150, 30);

        botaoLancar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botaoLancar.setText("Lançar ");
        botaoLancar.setMaximumSize(new java.awt.Dimension(150, 30));
        botaoLancar.setMinimumSize(new java.awt.Dimension(150, 30));
        botaoLancar.setPreferredSize(new java.awt.Dimension(150, 30));
        botaoLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLancarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoLancar);
        botaoLancar.setBounds(311, 688, 150, 30);

        try {
            boxDataPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        boxDataPagamento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxDataPagamento.setMaximumSize(new java.awt.Dimension(200, 30));
        boxDataPagamento.setMinimumSize(new java.awt.Dimension(200, 30));
        boxDataPagamento.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(boxDataPagamento);
        boxDataPagamento.setBounds(822, 194, 125, 30);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(680, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(680, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 80));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Controle Financeiro");
        jLabel1.setMaximumSize(new java.awt.Dimension(335, 45));
        jLabel1.setMinimumSize(new java.awt.Dimension(335, 45));
        jLabel1.setPreferredSize(new java.awt.Dimension(335, 45));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 11, 1004, 80);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Data de Vencimento");
        jLabel10.setMaximumSize(new java.awt.Dimension(200, 20));
        jLabel10.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(604, 247, 200, 20);

        try {
            boxDataVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        boxDataVencimento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxDataVencimento.setMaximumSize(new java.awt.Dimension(200, 30));
        boxDataVencimento.setMinimumSize(new java.awt.Dimension(200, 30));
        boxDataVencimento.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(boxDataVencimento);
        boxDataVencimento.setBounds(822, 237, 125, 30);

        boxValorMensal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxValorMensal.setMaximumSize(new java.awt.Dimension(200, 30));
        boxValorMensal.setMinimumSize(new java.awt.Dimension(200, 30));
        boxValorMensal.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(boxValorMensal);
        boxValorMensal.setBounds(286, 290, 100, 30);

        boxValorPago.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxValorPago.setMaximumSize(new java.awt.Dimension(200, 30));
        boxValorPago.setMinimumSize(new java.awt.Dimension(200, 30));
        boxValorPago.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(boxValorPago);
        boxValorPago.setBounds(822, 285, 100, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/200x100.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(778, 618, 190, 100);

        NomeAluno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(NomeAluno);
        NomeAluno.setBounds(286, 196, 300, 28);

        setSize(new java.awt.Dimension(1040, 806));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxAlunosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAlunosCadastradosActionPerformed
       
        String aux;
       aux = (String) boxAlunosCadastrados.getSelectedItem();       
       ResultSet rs = null;  
       
        try {
            rs = a.buscarMatricula(aux);             
            if (!rs.first()) {
                JOptionPane.showMessageDialog(null, "Aluno"
                        + " não encontrada!");
            } else {
                NomeAluno.setText(rs.getString("nome"));
                NomeAluno.setEditable(false);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ControleFinanceiroTela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ControleFinanceiroTela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boxAlunosCadastradosActionPerformed

    private void botaoLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLancarActionPerformed
        if (!boxValorMensal.getText().equals("")) {
            cf.setCodMatricula(Integer.parseInt((String)boxAlunosCadastrados.getSelectedItem()));
            cf.setPlanoMensalidade((String)boxPlano.getSelectedItem());
            cf.setValorMensalidade(Float.parseFloat(boxValorMensal.getText()));
            cf.setFormaPagamento((String)boxMetodo.getSelectedItem());
            cf.setDataPagamento(boxDataPagamento.getText());
            cf.setValorPago(Float.parseFloat(boxValorPago.getText()));
            cf.setDataVencimento(boxDataVencimento.getText());
            if(boxValorMensal.getText() != null){
                cf.setSituacaoPagamento("Pago");
            }else{
            cf.setSituacaoPagamento("Devendo");
                    }             
           
            try {
                cf.inserir();
                JOptionPane.showMessageDialog(null,
                        "Controle Financeiro Efetuado Com Sucesso!!");
               dispose();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ControleFinanceiroTela.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ControleFinanceiroTela.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    
    }//GEN-LAST:event_botaoLancarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleFinanceiroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleFinanceiroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleFinanceiroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleFinanceiroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleFinanceiroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomeAluno;
    private javax.swing.JButton botaoLancar;
    private javax.swing.JComboBox<String> boxAlunosCadastrados;
    private javax.swing.JFormattedTextField boxDataPagamento;
    private javax.swing.JFormattedTextField boxDataVencimento;
    private javax.swing.JComboBox<String> boxMetodo;
    private javax.swing.JComboBox<String> boxPlano;
    private javax.swing.JTextField boxValorMensal;
    private javax.swing.JTextField boxValorPago;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
