package Telas;

import Classes.Alunos;
import Classes.ControleFinanceiro;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class GerenciarAlunos extends javax.swing.JFrame {

    private Alunos a = new Alunos();
    private ControleFinanceiro cf = new ControleFinanceiro();

    public GerenciarAlunos() {
        ResultSet rs;
        initComponents();
        try {
            rs = a.selecionarAluno();
            if (rs != null) {
                while (rs.next()) {
                    boxMatriculas.addItem(rs.getString("matricula"));
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum"
                        + " Aluno cadastrado!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GerenciarAlunos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        boxNome = new javax.swing.JTextField();
        boxProfe = new javax.swing.JTextField();
        alterar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        boxTurma = new javax.swing.JTextField();
        boxDias = new javax.swing.JTextField();
        boxTurno = new javax.swing.JTextField();
        boxModal = new javax.swing.JTextField();
        boxSituacao = new javax.swing.JComboBox<>();
        boxMatriculas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boxDataNasci = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        boxDataAdmissao = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Alunos");
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Nome");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 200, 47, 22);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Modalidade");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 250, 93, 22);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Turno");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 300, 48, 22);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Dias");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(470, 350, 36, 22);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Turma");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 390, 52, 22);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Professor");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(430, 440, 77, 22);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Situação");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 490, 70, 22);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Data de Nascimento");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(340, 540, 162, 22);

        boxNome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxNome.setMaximumSize(new java.awt.Dimension(200, 30));
        boxNome.setMinimumSize(new java.awt.Dimension(200, 30));
        boxNome.setPreferredSize(new java.awt.Dimension(200, 30));
        boxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNomeActionPerformed(evt);
            }
        });
        getContentPane().add(boxNome);
        boxNome.setBounds(520, 200, 300, 30);

        boxProfe.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxProfe.setMaximumSize(new java.awt.Dimension(200, 30));
        boxProfe.setMinimumSize(new java.awt.Dimension(200, 30));
        boxProfe.setPreferredSize(new java.awt.Dimension(300, 30));
        boxProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxProfeActionPerformed(evt);
            }
        });
        getContentPane().add(boxProfe);
        boxProfe.setBounds(520, 440, 300, 30);

        alterar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alterar.setText("Alterar");
        alterar.setMaximumSize(new java.awt.Dimension(150, 30));
        alterar.setMinimumSize(new java.awt.Dimension(150, 30));
        alterar.setPreferredSize(new java.awt.Dimension(150, 30));
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        getContentPane().add(alterar);
        alterar.setBounds(280, 670, 115, 30);

        excluir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        excluir.setText("Excluir");
        excluir.setMaximumSize(new java.awt.Dimension(150, 30));
        excluir.setMinimumSize(new java.awt.Dimension(150, 30));
        excluir.setPreferredSize(new java.awt.Dimension(150, 30));
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        getContentPane().add(excluir);
        excluir.setBounds(640, 670, 115, 30);

        cancelar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setMaximumSize(new java.awt.Dimension(150, 30));
        cancelar.setMinimumSize(new java.awt.Dimension(150, 30));
        cancelar.setPreferredSize(new java.awt.Dimension(150, 30));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(460, 670, 115, 30);

        boxTurma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxTurma.setMaximumSize(new java.awt.Dimension(200, 30));
        boxTurma.setMinimumSize(new java.awt.Dimension(200, 30));
        boxTurma.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(boxTurma);
        boxTurma.setBounds(520, 390, 150, 30);

        boxDias.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxDias.setMaximumSize(new java.awt.Dimension(200, 30));
        boxDias.setMinimumSize(new java.awt.Dimension(200, 30));
        boxDias.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(boxDias);
        boxDias.setBounds(520, 340, 300, 30);

        boxTurno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxTurno.setMaximumSize(new java.awt.Dimension(200, 30));
        boxTurno.setMinimumSize(new java.awt.Dimension(200, 30));
        boxTurno.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(boxTurno);
        boxTurno.setBounds(520, 290, 150, 30);

        boxModal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxModal.setMaximumSize(new java.awt.Dimension(200, 30));
        boxModal.setMinimumSize(new java.awt.Dimension(200, 30));
        boxModal.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(boxModal);
        boxModal.setBounds(520, 250, 150, 30);

        boxSituacao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativado", "Desativado" }));
        boxSituacao.setPreferredSize(new java.awt.Dimension(150, 30));
        boxSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSituacaoActionPerformed(evt);
            }
        });
        getContentPane().add(boxSituacao);
        boxSituacao.setBounds(520, 490, 150, 30);

        boxMatriculas.setMaximumSize(new java.awt.Dimension(150, 30));
        boxMatriculas.setMinimumSize(new java.awt.Dimension(150, 30));
        boxMatriculas.setPreferredSize(new java.awt.Dimension(150, 30));
        boxMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMatriculasActionPerformed(evt);
            }
        });
        getContentPane().add(boxMatriculas);
        boxMatriculas.setBounds(520, 120, 300, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Pesquisar Matrícula");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 120, 160, 22);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(680, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(680, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 80));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciar Aluno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 9, 1010, 66);

        try {
            boxDataNasci.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        boxDataNasci.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxDataNasci.setMinimumSize(new java.awt.Dimension(6, 30));
        boxDataNasci.setPreferredSize(new java.awt.Dimension(56, 30));
        boxDataNasci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDataNasciActionPerformed(evt);
            }
        });
        getContentPane().add(boxDataNasci);
        boxDataNasci.setBounds(520, 530, 150, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/200x100.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(790, 600, 190, 100);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Data de Admissão");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 590, 145, 22);

        try {
            boxDataAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        boxDataAdmissao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boxDataAdmissao.setMinimumSize(new java.awt.Dimension(6, 30));
        boxDataAdmissao.setPreferredSize(new java.awt.Dimension(56, 30));
        boxDataAdmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDataAdmissaoActionPerformed(evt);
            }
        });
        getContentPane().add(boxDataAdmissao);
        boxDataAdmissao.setBounds(520, 580, 150, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        String aux;
        aux = (String) boxMatriculas.getSelectedItem();
        a.setNome(boxNome.getText());
        a.setTurma(boxTurma.getText());
        a.setProfessor(boxProfe.getText());
        a.setDataNascimento(boxDataNasci.getText());
        a.setTurno(boxTurno.getText());
        a.setDias(boxDias.getText());
        a.setModalidade(boxModal.getText());
        a.setSituacao((String) boxSituacao.getSelectedItem());
        a.setDataAdmissao(boxDataAdmissao.getText());
        try {
            a.alterar(aux);
            JOptionPane.showMessageDialog(null, "Aluno alterado "
                    + "com sucesso!");
            dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GerenciarAlunos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_alterarActionPerformed

    private void boxMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMatriculasActionPerformed
        String aux;
        aux = (String) boxMatriculas.getSelectedItem();
        ResultSet rs = null;
        try {
            rs = a.buscarMatricula(aux);
            if (!rs.first()) {
                JOptionPane.showMessageDialog(null, "Aluno"
                        + " não encontrado!");
            } else {
                boxNome.setText(rs.getString("nome"));
                boxModal.setText(rs.getString("modalidade"));
                boxTurno.setText(rs.getString("turno"));
                boxDias.setText(rs.getString("dias"));
                boxTurma.setText(rs.getString("turma"));
                boxProfe.setText(rs.getString("professor"));
                boxSituacao.setSelectedItem(rs.getString("situacao"));
                boxDataNasci.setText(rs.getString("DataNascimento"));
                boxDataAdmissao.setText(rs.getString("DataAdmissao"));              
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GerenciarAlunos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_boxMatriculasActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        String aux;
        aux = (String) boxMatriculas.getSelectedItem();
        a.setNome(boxNome.getText());
        a.setTurma(boxTurma.getText());
        a.setProfessor(boxProfe.getText());
        a.setDataNascimento(boxDataNasci.getText());
        a.setTurno(boxTurno.getText());
        a.setDias(boxDias.getText());
        a.setModalidade(boxModal.getText());
        a.setSituacao((String) boxSituacao.getSelectedItem());

        try {
            cf.excluir(aux);
            a.excluir(aux);

            JOptionPane.showMessageDialog(null, "Aluno excluído"
                    + " com sucesso!");
            dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GerenciarAlunos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void boxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNomeActionPerformed

    private void boxSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxSituacaoActionPerformed

    private void boxProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxProfeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxProfeActionPerformed

    private void boxDataNasciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDataNasciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxDataNasciActionPerformed

    private void boxDataAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDataAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxDataAdmissaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JFormattedTextField boxDataAdmissao;
    private javax.swing.JFormattedTextField boxDataNasci;
    private javax.swing.JTextField boxDias;
    private javax.swing.JComboBox<String> boxMatriculas;
    private javax.swing.JTextField boxModal;
    private javax.swing.JTextField boxNome;
    private javax.swing.JTextField boxProfe;
    private javax.swing.JComboBox<String> boxSituacao;
    private javax.swing.JTextField boxTurma;
    private javax.swing.JTextField boxTurno;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton excluir;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
